Fixed getAllBalances
techinpark/upbitBar pull request #2
Opened 2021-03-18 06:51 UTC by vkcldhkd

안녕하세요 :)
업비트를 매번 열어보는 귀차니즘을 해결해주셔서 감사합니다 ㅎㅎ
약간의 기능을 추가해봤습니다.

1. 업비트에서 거래 가능한 코인 조회
2. 코인이름 나오는 형식 변경

2021-03-19 08:09 UTC, vkcldhkd commented
<img width="318" alt="스크린샷 2021-03-19 오후 5 09 22" src="https://user-images.githubusercontent.com/6158125/111749949-da7d7a00-88d5-11eb-98d5-99194e85c1d9.png">

2021-03-19 17:47 UTC, techinpark commented
@vkcldhkd 좋은 기여해주셔서 감사합니다!  컨플릭트 해결 이후 머지 하도록 하겠습니다 👍

2021-03-19 17:58 UTC, techinpark requested changes

2021-03-19 17:58 UTC, techinpark commented on upbitBar.xcodeproj/xcuserdata/sung.xcuserdatad/xcschemes/xcschememanagement.plist
> +</plist>
- UserInterfaceState.xcuserstate
- xcschememanagement.plist 

불필요한 파일이 포함된것 같습니다 제거 부탁드려도 될까요?

2021-03-19 17:58 UTC, techinpark commented on Sources/AppDelegate.swift
> +            .filter{ market -> Bool in availableMarkets.filter{ $0 == market }.first != nil }
기존에 구현을 못한 부분인데 깔끔하게 정리해주셔서 감사합니다! 👍

2021-03-19 17:58 UTC, techinpark commented on Sources/AppDelegate.swift
> +            var tempDict: [String: Market] = [: ]
```suggestion
            var tempDict: [String: Market] = [:]
```
불필요한 공백이 들어간 것 같습니다.

2021-03-19 17:58 UTC, techinpark commented on Sources/AppDelegate.swift
> +        var myCurrency: [String: Market]{
```suggestion 
        var myCurrency: [String: Market] {
```

2021-03-19 17:58 UTC, techinpark commented on Sources/AppDelegate.swift
> +            for currencyItem in currency{
```suggestion
            for currencyItem in currency {
```

2021-03-19 17:58 UTC, techinpark commented on Sources/Networking/UpbitServices.swift
> +        do{
```suggestion
        do {
```

2021-03-19 17:58 UTC, techinpark commented on Sources/Networking/UpbitServices.swift
> +        do{
```suggestion
        do {
```

2021-03-19 17:58 UTC, techinpark commented on Sources/Networking/UpbitServices.swift
> +        }catch let error{
```suggestion 
        } catch {
```

2021-03-19 17:58 UTC, techinpark commented on Sources/Networking/UpbitServices.swift
> +        }catch let error{
```suggestion 
        } catch {
```

2021-03-22 01:47 UTC, vkcldhkd commented
Ticker 모델과 공백, 컨플릭트를 수정하였습니다 :) 확인부탁드립니다

2021-03-22 01:54 UTC, vkcldhkd commented on upbitBar.xcodeproj/xcuserdata/sung.xcuserdatad/xcschemes/xcschememanagement.plist
> +</plist>
말씀해주신 파일들은 어떻게 제거해야할까요? ㅎㅎ... 제가 따로 추가한적이 없어서 제거방법을 모르겠습니다 😅

2021-03-28 17:30 UTC, techinpark approved these changes
좋은기여 감사드립니다 다음버전(v1.2) 에 반영될 예정입니다 🚀

2021-03-28 17:30 UTC, merged